const COUNTRY_CODES: Record<string, string> = {
  "united states": "us",
  "united states of america": "us",
  usa: "us",
  us: "us",
  canada: "ca",
  mexico: "mx",
  "united kingdom": "gb",
  uk: "gb",
  "great britain": "gb",
  england: "gb",
  scotland: "gb",
  wales: "gb",
  ireland: "ie",
  france: "fr",
  germany: "de",
  spain: "es",
  italy: "it",
  switzerland: "ch",
  austria: "at",
  netherlands: "nl",
  holland: "nl",
  belgium: "be",
  portugal: "pt",
  monaco: "mc",
  turkey: "tr",
  turkiye: "tr",
  türkiye: "tr",
  belarus: "by",
  russia: "ru",
  ukraine: "ua",
  poland: "pl",
  "czech republic": "cz",
  czechia: "cz",
  hungary: "hu",
  greece: "gr",
  sweden: "se",
  norway: "no",
  denmark: "dk",
  finland: "fi",
  iceland: "is",
  qatar: "qa",
  "united arab emirates": "ae",
  uae: "ae",
  "saudi arabia": "sa",
  india: "in",
  "sri lanka": "lk",
  maldives: "mv",
  malaysia: "my",
  singapore: "sg",
  china: "cn",
  taiwan: "tw",
  laos: "la",
  loas: "la",
  vietnam: "vn",
  "south korea": "kr",
  korea: "kr",
  "north korea": "kp",
  japan: "jp",
  philippines: "ph",
  indonesia: "id",
  thailand: "th",
  cambodia: "kh",
  myanmar: "mm",
  burma: "mm",
  australia: "au",
  "new zealand": "nz",
  "french polynesia": "pf",
  "dominican republic": "do",
  jamaica: "jm",
  cuba: "cu",
  haiti: "ht",
  "puerto rico": "pr",
  brazil: "br",
  argentina: "ar",
  chile: "cl",
  peru: "pe",
  colombia: "co",
  venezuela: "ve",
  ecuador: "ec",
  uruguay: "uy",
  paraguay: "py",
  bolivia: "bo",
  "south africa": "za",
  egypt: "eg",
  morocco: "ma",
  kenya: "ke",
  nigeria: "ng",
  israel: "il",
  jordan: "jo",
  lebanon: "lb",
  iran: "ir",
  iraq: "iq",
  pakistan: "pk",
  bangladesh: "bd",
  nepal: "np",
  afghanistan: "af",
  kazakhstan: "kz",
};

export function toCountryCode(name: string): string | undefined {
  return COUNTRY_CODES[name.trim().toLowerCase()];
}

export function detectCountryFromLine(line: string): string | undefined {
  const segments = line.split(",");
  const lastSegment = segments[segments.length - 1];
  return toCountryCode(lastSegment);
}
